### PR TITLE
ci: scan docker image on CVEs

### PR DESCRIPTION
**Pull request by ikheifets-splunk**
@alltilla Implemented issue [docker image CVE scanning on CI](https://github.com/axoflow/axosyslog/issues/190)

### CODE REVIEW

**Review by MrAnno — APPROVED** [review]
Perfect, thank you :)

We may want to add this to the nightly job as well.

**Comment by MrAnno** [comment]
Could you rebase your PR against the current `main`, please?

**Comment by ikheifets-splunk** [comment]
@MrAnno sure, rebased

**Review by MrAnno — APPROVED** [review]
Thanks.

**Pull request merged**
