### PR TITLE
Revert "dbld: disable smtp on debian-testing"

### PR DESCRIPTION
**Pull request by MrAnno**
This reverts commit 55c821f39e06e27dce9d9059a97129cb59d3cdc3.

https://tracker.debian.org/news/1568959/libesmtp-110-32-migrated-to-testing/

### CODE REVIEW

**Review by alltilla — DISMISSED** [review]
Shouldn't we revert this, too? https://github.com/axoflow/axosyslog/commit/cee891d24d20fd8a9ec271cabc51d0b76224e707

**Comment by MrAnno** [comment]
I don't know why this was submitted in a separate PR.. I will revert that too, thanks.

**Review by alltilla — APPROVED** [review]

**Comment by MrAnno** [comment]
CI will be green after the rebuild on `main`.

**Comment by alltilla** [comment]
I think it is okay to merge this with a failing CI, the devshell image is still not cached/rebuilt in CI :S

**Pull request merged**
