### PR TITLE
cfg-grammar.y: add location reporting to bison debug

### PR DESCRIPTION
**Pull request by bazsi**
This will add location information to the grammar debug output.

### CODE REVIEW

**Comment by alltilla** [comment]
This did not work for me at all.

To make it work I had to set the `YY_LOCATION_PRINT` macro instead of `YYLOCATION_PRINT`, and had to change the signature as well from `main_location_print (FILE *yyo, YYLTYPE const * const yylocp)` to `main_location_print (FILE *yyo, YYLTYPE yylocp)`.

I can see that `YYLOCATION_PRINT` is documented, but my generated c code used `YY_LOCATION_PRINT` everywhere.

@bazsi Have you read anything about this?

FTR:
```
$ bison --version
bison (GNU Bison) 3.7.6
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bazsi** [comment]
This might be a bison version issue. I found the stuff while reading the
generated source.

I'll check what I have as bison, but I think that's relatively recent as
dbld uses Debian testing.

**Comment by bazsi** [comment]
@alltilla added bison dependency check as requested IRL.

**Comment by alltilla** [comment]
I have tested the old bison version, it behaves as expected.

**Review by alltilla — DISMISSED** [review]

**Review by alltilla — APPROVED** [review]

**Pull request merged**
